name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.2, 4.6]
        jdk: [8, 11]
    env:
      repo: "govpf/sonar-scanner"
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Compute tags
      env:
        repo: ${{ env.repo }}
        version: ${{ matrix.version }}
        jdk: ${{ matrix.jdk }}
      run: |
        TAGS="${repo}:${version}-jdk-${jdk}"
        if [[ $jdk == '8' ]]; then
          TAGS+=",${repo}:${version}"
        fi
        echo 'docker_tags<<EOF' >> $GITHUB_ENV
        echo "$TAGS" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Build
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./${{ matrix.version }}/jdk-${{ matrix.jdk }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: ${{ env.docker_tags }}
